### ISSUE TITLE
fp-ts-local-storage lacks of ES6 modules and paths should not be rewritten

### ISSUE THREAD

**Issue by StefanoMagrassi** [gcanti/import-path-rewrite#2]
### Current Behavior

The script tries to rewrite also [`fp-ts-local-storage` paths](https://github.com/gcanti/import-path-rewrite/blob/master/src/index.ts#L31) but currently the package does not publish modules in ES6 format.

### Suggested solution(s)

The `fp-ts-local-storage` should be removed from the list of packages until also the ES6 modules (ref https://github.com/gcanti/fp-ts-local-storage/pull/3) will not be published

**Comment by gcanti** [comment]
Solved in https://github.com/gcanti/fp-ts-local-storage/releases/tag/1.0.0
